# Generated by Django 3.2.4 on 2021-06-29 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vehicles', 'VEHICLES'), ('phones', 'PHONES'), ('property', 'PROPERTY'), ('electronics', 'ELECTRONICS'), ('fashion', 'FASHION')], default='phones', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='api.category'),
        ),
    ]
