# Generated by Django 3.2.4 on 2021-06-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210629_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEHICLES', 'vehicles'), ('PHONES', 'phones'), ('PROPERTY', 'property'), ('ELECTRONICS', 'electronics'), ('FASHION', 'fashion')], default='phones', max_length=100),
        ),
    ]
